### ISSUE TITLE
CSSフレームワークの導入

### ISSUE THREAD

**Issue by Mod12d** [Mod12d/clean_network#21]
tailwindからmantineなど
(しまぶーさんがmantine薦められてたので、mantine気になってます)
参考
https://dev.classmethod.jp/articles/mantine-hooks/

ハイブリッドで使用できるかも。

**Comment by yoko-at-home** [comment]
手前味噌ですが、ほんの少しneumorphismの要素を取り入れた[自分こんな作品](https://www.canon-cat.com)作りました。
claymorphism興味あります〜

**Comment by Mod12d** [comment]
おお〜すごいおしゃれですね！
