### ISSUE TITLE
アーキテクチャーの設計

### ISSUE THREAD

**Issue by Mod12d** [Mod12d/clean_network#30]
https://zenn.dev/eringiv3/articles/c7146e720bc457
https://qiita.com/yuno_miyako/items/fad33456d9c32d8f4483

**Comment by Mod12d** [comment]
next.js | flask(python) | neo4j

**Comment by Mod12d** [comment]
①neo4jからデータを取得
react <-neo4j
python(flask) <-neo4j
②neo4jにデータ更新
python(flask)->neo4j
③twttterのデータ更新
python(flask)->twitter

**Comment by Mod12d** [comment]
これはタスクというより検討事項なので、
ディスカッションに移動

**Comment by gotoh-poclab** [comment]
④twitterからデータ取得して分析(クラスタリング）は、以下のような分析でしょうか。
https://www.youtube.com/watch?v=9likd_DT4Lo

**Comment by gotoh-poclab** [comment]
デプロイ先ですが、neo4j　と　GCPだと以下のようなサイトが出てきました。
https://www.opensourcetech.tokyo/entry/20190417/1555513017
