### ISSUE TITLE
ユーザアイコンを作成

### ISSUE THREAD

**Issue by Mod12d** [Mod12d/clean_network#34]

**Comment by yoko-at-home** [comment]
＠Mod12d こんな感じのアイコンをLottieで見つけて作ってみましたが、Figmaのアイコンを実装すべきですか？
https://user-images.githubusercontent.com/61738591/179343396-f821ba03-73a8-4e31-b8d2-70a3115e852c.mov
<img width="45" alt="Screenshot 2022-07-16 at 15 38 23" src="https://user-images.githubusercontent.com/61738591/179343423-e9985fd9-2bf5-41b7-890b-2963760a4037.png">

**Comment by Mod12d** [comment]
良いですね！
yokoさんの見つけていただい方で良いと思います！
(Figmaは後で修正しないとですが）
