### ISSUE TITLE
typescriptに変換

### ISSUE THREAD

**Issue by Mod12d** [Mod12d/clean_network#4]

**Comment by yoko-at-home** [comment]
tsconfig.jsonを作成してプロジェクトをスタートさせましたが、次のオプションで怒られます。
```resolveJsonModule```
``Option '--resolveJsonModule' cannot be specified without 'node' module resolution strategy.``
<img width="387" alt="Screenshot 2022-06-19 at 13 46 30" src="https://user-images.githubusercontent.com/61738591/174466261-2fa62420-cf2f-40f6-9b47-40f55c1308cc.png">

以下の参照先みましたが、よく分かりません。
https://www.typescriptlang.org/tsconfig#resolveJsonModule

QinTodoではこの設定に対して何かしていることはなかったようです。

**Comment by yoko-at-home** [comment]
"moduleResolution": "node",を設定したらエラーが消えました🙌
<img width="632" alt="Screenshot 2022-06-19 at 14 09 09" src="https://user-images.githubusercontent.com/61738591/174466873-0009110f-4186-48b1-9eeb-9fdc6abfc581.png">
。
